Repository SciSharp/TensorFlow.NET, pull requests merged in 2023-09, with the labels that each got.

#1169 add: loading pickled npy file for imdb dataset loader
  src/TensorFlowNET.Core/NumPy/Implementation/NumPyImpl.Creation.cs
  src/TensorFlowNET.Core/NumPy/Implementation/NumPyImpl.load.cs
  src/TensorFlowNET.Core/NumPy/Implementation/RandomizedImpl.cs
  src/TensorFlowNET.Core/NumPy/NDArrayConverter.cs
  src/TensorFlowNET.Core/NumPy/Pickle/DTypePickleWarpper.cs
  src/TensorFlowNET.Core/NumPy/Pickle/DtypeConstructor.cs
  src/TensorFlowNET.Core/NumPy/Pickle/MultiArrayConstructor.cs
  src/TensorFlowNET.Core/NumPy/Pickle/MultiArrayPickleWarpper.cs
  src/TensorFlowNET.Core/Numpy/Numpy.cs
  src/TensorFlowNET.Core/Tensorflow.Binding.csproj
  src/TensorFlowNET.Core/tensorflow.cs
  src/TensorFlowNET.Keras/Datasets/Imdb.cs
  src/TensorFlowNET.Keras/Utils/data_utils.cs
  test/TensorFlowNET.UnitTest/Dataset/DatasetTest.cs
Labels: bug

#1171 fix: model does not stop on stop_training == true #1170
  src/TensorFlowNET.Keras/Engine/Model.Fit.cs
Labels: keras

#1172 cached_session for graph tests
  test/TensorFlowNET.Graph.UnitTest/ControlFlowTest/WhileContextTestCase.cs
  test/TensorFlowNET.Graph.UnitTest/GradientTest/GradientTest.cs
  test/TensorFlowNET.Graph.UnitTest/PythonTest.cs
Labels: enhancement
