Repository SciSharp/TensorFlow.NET, pull requests merged in 2023-04, with the labels that each got.

#1023 Fix the error when saving model with GPU.
  src/TensorFlowNET.Core/Checkpoint/SaveUtilV1.cs
  src/TensorFlowNET.Core/Checkpoint/checkpoint.cs
  src/TensorFlowNET.Core/Checkpoint/functional_saver.cs
  src/TensorFlowNET.Core/Contexts/Context.Device.cs
  src/TensorFlowNET.Core/Contexts/Context.cs
  src/TensorFlowNET.Core/Contexts/EagerDeviceContext.cs
  src/TensorFlowNET.Core/Device/DeviceSpec.cs
  src/TensorFlowNET.Core/Device/DeviceUtils.cs
  src/TensorFlowNET.Core/Graphs/Graph.cs
  src/TensorFlowNET.Core/Graphs/GraphDeviceContext.cs
  src/TensorFlowNET.Core/Training/Saving/ResourceVariableSaveable.cs
  src/TensorFlowNET.Core/Training/Saving/SavedModel/loader.cs
  src/TensorFlowNET.Core/Variables/BaseResourceVariable.cs
  src/TensorFlowNET.Core/Variables/UninitializedVariable.cs
  src/TensorFlowNET.Core/ops.cs
Labels: bug

#1027 Fix the error when loading VGG19.
  src/TensorFlowNET.Core/Keras/ArgsDefinition/AutoSerializeLayerArgs.cs
  src/TensorFlowNET.Core/Keras/Common/CustomizedShapeJsonConverter.cs
  src/TensorFlowNET.Core/Tensorflow.Binding.csproj
  src/TensorFlowNET.Core/Training/Saving/SavedModel/loader.cs
  src/TensorFlowNET.Keras/Utils/generic_utils.cs
  test/TensorFlowNET.Keras.UnitTest/SaveModel/SequentialModelLoad.cs
Labels: bug

#1029 Fix the error of example caused by #1022
  TensorFlow.NET.sln
  Tensorflow.Common/Tensorflow.Common.csproj
  src/TensorFlowNET.Core/Extensions/DictionaryExtension.cs
  src/TensorFlowNET.Core/Extensions/NamedTuple.cs
  src/TensorFlowNET.Core/Extensions/OneofExtension.cs
  src/TensorFlowNET.Core/Tensorflow.Binding.csproj
  src/TensorFlowNET.Core/Util/ProtoUtils.cs
  src/TensorFlowNET.Core/Variables/ResourceVariable.cs
Labels: bug

#1031 Fix the error when loading Conv1D layer with initialzier.
  src/TensorFlowNET.Core/APIs/tf.init.cs
  src/TensorFlowNET.Core/Keras/ArgsDefinition/Convolution/ConvolutionalArgs.cs
  src/TensorFlowNET.Core/Keras/Common/CustomizedIInitializerJsonConverter.cs
  src/TensorFlowNET.Core/Keras/Common/CustomizedShapeJsonConverter.cs
  src/TensorFlowNET.Core/Operations/Initializers/GlorotUniform.cs
  src/TensorFlowNET.Core/Operations/Initializers/IInitializer.cs
  src/TensorFlowNET.Core/Operations/Initializers/VarianceScaling.cs
  src/TensorFlowNET.Core/Operations/gen_ops.cs
  src/TensorFlowNET.Keras/InitializersApi.cs
  src/TensorFlowNET.Keras/Layers/Convolution/Conv1D.cs
  src/TensorFlowNET.Keras/Layers/Convolution/Conv2D.cs
  src/TensorFlowNET.Keras/Layers/Convolution/Conv2DTranspose.cs
Labels: bug, model save/load

#1030 Add set_weights and get_weighst APIs
  src/TensorFlowNET.Core/Keras/Layers/ILayer.cs
  src/TensorFlowNET.Core/Operations/NnOps/RNNCell.cs
  src/TensorFlowNET.Keras/Engine/Layer.cs
Labels: enhancement, api

#1032 Fix the error of loading model saved before tf2.5.
  src/TensorFlowNET.Core/APIs/tf.saved_model.cs
  src/TensorFlowNET.Core/Graphs/FuncGraph.cs
  src/TensorFlowNET.Core/Keras/Engine/IOptimizer.cs
  src/TensorFlowNET.Core/Operations/Operation.cs
  src/TensorFlowNET.Core/Tensors/tensor_util.cs
  src/TensorFlowNET.Core/Trackables/TrackableConstant.cs
  src/TensorFlowNET.Core/Training/Saving/SavedModel/RevivedTypes.cs
  src/TensorFlowNET.Core/Training/Saving/SavedModel/SaveableView.cs
  src/TensorFlowNET.Core/Training/Saving/SavedModel/function_deserialization.cs
  src/TensorFlowNET.Core/Training/Saving/SavedModel/loader.cs
  src/TensorFlowNET.Core/Training/Saving/SavedModel/loader.static.cs
  src/TensorFlowNET.Core/Training/TrackableUtils.cs
  src/TensorFlowNET.Core/Variables/BaseResourceVariable.cs
  src/TensorFlowNET.Core/Variables/ResourceVariable.Operators.cs
  src/TensorFlowNET.Keras/BackendImpl.cs
  src/TensorFlowNET.Keras/KerasInterface.cs
  src/TensorFlowNET.Keras/Optimizers/OptimizerV2.cs
  src/TensorFlowNET.Keras/Optimizers/RestoredOptimizer.cs
  test/TensorFlowNET.Keras.UnitTest/SaveModel/SequentialModelLoad.cs
Labels: bug, model save/load

#1033 Change type of BuildInputShape and BatchInputShape
  src/TensorFlowNET.Core/Extensions/JObjectExtensions.cs
  src/TensorFlowNET.Core/Framework/Models/TensorSpec.cs
  src/TensorFlowNET.Core/Keras/Activations/Activations.cs
  src/TensorFlowNET.Core/Keras/ArgsDefinition/AutoSerializeLayerArgs.cs
  src/TensorFlowNET.Core/Keras/ArgsDefinition/Core/InputLayerArgs.cs
  src/TensorFlowNET.Core/Keras/ArgsDefinition/LayerArgs.cs
  src/TensorFlowNET.Core/Keras/Layers/ILayer.cs
  src/TensorFlowNET.Core/Keras/Saving/Json/CustomizedActivationJsonConverter.cs
  src/TensorFlowNET.Core/Keras/Saving/Json/CustomizedAxisJsonConverter.cs
  src/TensorFlowNET.Core/Keras/Saving/Json/CustomizedDTypeJsonConverter.cs
  src/TensorFlowNET.Core/Keras/Saving/Json/CustomizedIInitializerJsonConverter.cs
  src/TensorFlowNET.Core/Keras/Saving/Json/CustomizedKerasShapesWrapperJsonConverter.cs
  src/TensorFlowNET.Core/Keras/Saving/Json/CustomizedNodeConfigJsonConverter.cs
  src/TensorFlowNET.Core/Keras/Saving/Json/CustomizedShapeJsonConverter.cs
  src/TensorFlowNET.Core/Keras/Saving/KerasShapesWrapper.cs
  src/TensorFlowNET.Core/Keras/Saving/ModelConfig.cs
  src/TensorFlowNET.Core/Keras/Saving/NodeConfig.cs
  src/TensorFlowNET.Core/NumPy/Axis.cs
  src/TensorFlowNET.Core/Numpy/Shape.cs
  src/TensorFlowNET.Core/Operations/Initializers/IInitializer.cs
  src/TensorFlowNET.Core/Operations/NnOps/RNNCell.cs
  src/TensorFlowNET.Core/Tensors/TF_DataType.cs
  src/TensorFlowNET.Core/Training/Saving/SavedModel/function_deserialization.cs
  src/TensorFlowNET.Core/Training/Saving/SavedModel/loader.cs
  src/TensorFlowNET.Keras/Engine/Functional.FromConfig.cs
  src/TensorFlowNET.Keras/Engine/Functional.GetConfig.cs
  src/TensorFlowNET.Keras/Engine/Layer.cs
  src/TensorFlowNET.Keras/Engine/Model.Build.cs
  src/TensorFlowNET.Keras/Engine/Sequential.cs
  src/TensorFlowNET.Keras/Layers/Activation/ELU.cs
  src/TensorFlowNET.Keras/Layers/Activation/Exponential.cs
  src/TensorFlowNET.Keras/Layers/Activation/SELU.cs
  src/TensorFlowNET.Keras/Layers/Attention/Attention.cs
  src/TensorFlowNET.Keras/Layers/Convolution/Conv2DTranspose.cs
  src/TensorFlowNET.Keras/Layers/Convolution/Convolutional.cs
  src/TensorFlowNET.Keras/Layers/Core/Dense.cs
  src/TensorFlowNET.Keras/Layers/Core/EinsumDense.cs
  src/TensorFlowNET.Keras/Layers/Core/Embedding.cs
  src/TensorFlowNET.Keras/Layers/Core/InputLayer.cs
  src/TensorFlowNET.Keras/Layers/Merging/Concatenate.cs
  src/TensorFlowNET.Keras/Layers/Merging/Merge.cs
  src/TensorFlowNET.Keras/Layers/Normalization/BatchNormalization.cs
  src/TensorFlowNET.Keras/Layers/Normalization/LayerNormalization.cs
  src/TensorFlowNET.Keras/Layers/Normalization/Normalization.cs
  src/TensorFlowNET.Keras/Layers/Preprocessing/PreprocessingLayer.cs
  src/TensorFlowNET.Keras/Layers/Preprocessing/TextVectorization.cs
  src/TensorFlowNET.Keras/Layers/Reshaping/Cropping1D.cs
  src/TensorFlowNET.Keras/Layers/Reshaping/Cropping2D.cs
  src/TensorFlowNET.Keras/Layers/Reshaping/Cropping3D.cs
  src/TensorFlowNET.Keras/Layers/Reshaping/Permute.cs
  src/TensorFlowNET.Keras/Layers/Rnn/RNN.cs
  src/TensorFlowNET.Keras/Layers/Rnn/SimpleRNN.cs
  src/TensorFlowNET.Keras/Layers/Rnn/SimpleRNNCell.cs
  src/TensorFlowNET.Keras/Models/ModelsApi.cs
  src/TensorFlowNET.Keras/Saving/KerasMetaData.cs
  src/TensorFlowNET.Keras/Saving/KerasModelConfig.cs
  src/TensorFlowNET.Keras/Saving/KerasObjectLoader.cs
  src/TensorFlowNET.Keras/Utils/base_layer_utils.cs
  src/TensorFlowNET.Keras/Utils/generic_utils.cs
  test/TensorFlowNET.Keras.UnitTest/Layers/ModelSaveTest.cs
Labels: api, model save/load

#1034 Add Tensorflow.NET.Hub
  TensorFlow.NET.sln
  src/TensorFlowNET.Core/Tensors/Tensors.cs
  src/TensorFlowNET.Core/Tensors/dtypes.cs
  src/TensorFlowNET.Keras/Engine/Layer.AddWeights.cs
  src/TensorFlowNET.Keras/Saving/KerasMetaData.cs
  src/TensorFlowNET.Keras/Saving/KerasObjectLoader.cs
  src/TensorFlowNET.Keras/Saving/SavedModel/RevivedInputLayer.cs
  src/TensorFlowNET.Keras/Saving/SavedModel/RevivedLayer.cs
  src/TensorFlowNET.Keras/Saving/SavedModel/RevivedNetwork.cs
  src/TensorflowNET.Hub/GcsCompressedFileResolver.cs
  src/TensorflowNET.Hub/HttpCompressedFileResolver.cs
  src/TensorflowNET.Hub/HttpUncompressedFileResolver.cs
  src/TensorflowNET.Hub/KerasLayer.cs
  src/TensorflowNET.Hub/Tensorflow.Hub.csproj
  src/TensorflowNET.Hub/file_utils.cs
  src/TensorflowNET.Hub/hub.cs
  src/TensorflowNET.Hub/module_v2.cs
  src/TensorflowNET.Hub/registry.cs
  src/TensorflowNET.Hub/resolver.cs
  src/TensorflowNET.Hub/tf_utils.cs
  test/TensorflowNET.Hub.Unittest/KerasLayerTest.cs
  test/TensorflowNET.Hub.Unittest/Tensorflow.Hub.Unittest.csproj
  test/TensorflowNET.Hub.Unittest/Usings.cs
Labels: enhancement, api, tf hub, break change

#1039 Fix (#1036) and adjust the keras unittest
  src/TensorFlowNET.Core/Operations/math_ops.cs
  test/TensorFlowNET.Keras.UnitTest/Callbacks/EarlystoppingTest.cs
  test/TensorFlowNET.Keras.UnitTest/EagerModeTestBase.cs
  test/TensorFlowNET.Keras.UnitTest/GradientTest.cs
  test/TensorFlowNET.Keras.UnitTest/InitializerTest.cs
  test/TensorFlowNET.Keras.UnitTest/Layers/ActivationTest.cs
  test/TensorFlowNET.Keras.UnitTest/Layers/AttentionTest.cs
  test/TensorFlowNET.Keras.UnitTest/Layers/CosineSimilarity.Test.cs
  test/TensorFlowNET.Keras.UnitTest/Layers/Huber.Test.cs
  test/TensorFlowNET.Keras.UnitTest/Layers/Layers.Convolution.Test.cs
  test/TensorFlowNET.Keras.UnitTest/Layers/Layers.Cropping.Test.cs
  test/TensorFlowNET.Keras.UnitTest/Layers/Layers.Merging.Test.cs
  test/TensorFlowNET.Keras.UnitTest/Layers/Layers.Reshaping.Test.cs
  test/TensorFlowNET.Keras.UnitTest/Layers/LayersTest.cs
  test/TensorFlowNET.Keras.UnitTest/Layers/LogCosh.Test.cs
  test/TensorFlowNET.Keras.UnitTest/Layers/MeanAbsoluteError.Test.cs
  test/TensorFlowNET.Keras.UnitTest/Layers/MeanAbsolutePercentageError.Test.cs
  test/TensorFlowNET.Keras.UnitTest/Layers/MeanSquaredError.Test.cs
  test/TensorFlowNET.Keras.UnitTest/Layers/MeanSquaredLogarithmicError.Test.cs
  test/TensorFlowNET.Keras.UnitTest/Layers/ModelSaveTest.cs
  test/TensorFlowNET.Keras.UnitTest/Layers/PoolingTest.cs
  test/TensorFlowNET.Keras.UnitTest/Losses/LossesTest.cs
  test/TensorFlowNET.Keras.UnitTest/Metrics/MetricsTest.cs
  test/TensorFlowNET.Keras.UnitTest/Model/ModelBuildTest.cs
  test/TensorFlowNET.Keras.UnitTest/Model/ModelLoadTest.cs
  test/TensorFlowNET.Keras.UnitTest/Model/ModelSaveTest.cs
  test/TensorFlowNET.Keras.UnitTest/MultiInputModelTest.cs
  test/TensorFlowNET.Keras.UnitTest/MultiThreadsTest.cs
  test/TensorFlowNET.Keras.UnitTest/OutputTest.cs
  test/TensorFlowNET.Keras.UnitTest/PreprocessingTests.cs
  test/TensorFlowNET.Keras.UnitTest/SaveModel/SequentialModelSave.cs
Labels: bug, test

#1043 Partially fix the error when crop image.
  src/TensorFlowNET.Core/Operations/image_ops_impl.cs
Labels: bug

#1044 Add the constructor of NDArray which reuses memory
  src/TensorFlowNET.Core/NumPy/Persistence/NpyFormat.cs
  src/TensorFlowNET.Core/Numpy/NDArray.Creation.cs
  src/TensorFlowNET.Core/Operations/array_ops.cs
  src/TensorFlowNET.Core/Tensors/c_api.tensor.cs
  src/TensorFlowNET.Core/Tensors/tensor_util.cs
Labels: bug, enhancement, numpy
